name: mini-uber

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: mini-uber-postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: mini_uber
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - mini-uber-pgdata:/var/lib/postgresql/data

volumes:
  mini-uber-pgdata:
